INSERT INTO TIPOPESSOA(Id, descricao)
values (1, "PESSOA FISICA")

INSERT INTO TIPOPESSOA(Id, descricao)
values (2, "PESSOA FISICA APOSENTADA")

INSERT INTO TIPOPESSOA(Id, descricao)
values (3, "PESSOA JURIDICA")





INSERT INTO TIPOEMPRESTIMO(Id, descricao)
values ("PESSOAL")


INSERT INTO TIPOPESSOA(Id, descricao)
values ("CONSIGNADO")

INSERT INTO TIPOPESSOA(Id, descricao)
values ("ROTATIVO")